### ISSUE TITLE
希望在生成的假消息开头加一个假消息的提示

### ISSUE THREAD

**Issue by omoidesu** [pcrbot/fake_message#1]
为了防止别有用心的人利用此功能传播谣言甚至做违法的事，希望可以加入提醒这个消息是假消息

=========

例如：
用户1 此消息为假消息balabala
用户1 xxx
用户2 xxxxxx
用户3 xxxx

**Comment by H-K-Y** [comment]
没必要，想造假消息的方法多得是，就算加了提醒也可以删掉提醒复制出去，和不加没区别
